### ISSUE TITLE
Ncmpcpp path

### ISSUE THREAD

**Issue by unai-ndz** [nicohman/raven#7]
Ncmpcpp supports both` $HOME/.ncmpcpp/config` and `$XDG_CONFIG_HOME/ncmpcpp/config`.
I think we should use `$XDG_CONFIG_HOME` or at least offer an option to configure this.

I can make a PR for this, but I'm unsure about adding a config option or not, what do you think?

**Comment by nicohman** [comment]
It could just check and see which one was already being used and swap it out based on that. Ill add that to the todo list.

**Comment by nicohman** [comment]
Pushed a commit to that rofi detects whether ~/.config/ncmpcpp or ~/.ncmpcpp exists and copies it to the correct directory there.

**Comment by unai-ndz** [comment]
So fast! Thanks.
